// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/logger.proto

package loggerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Request       string                 `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response      string                 `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LogRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *LogRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *LogRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_logger_proto protoreflect.FileDescriptor

const file_proto_logger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/logger.proto\x12\x06logger\"\xa8\x01\n" +
	"\n" +
	"LogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\arequest\x18\x04 \x01(\tR\arequest\x12\x1a\n" +
	"\bresponse\x18\x05 \x01(\tR\bresponse\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2C\n" +
	"\rLoggerService\x122\n" +
	"\aSaveLog\x12\x12.logger.LogRequest\x1a\x13.logger.LogResponseB\fZ\n" +
	"./loggerpbb\x06proto3"

var (
	file_proto_logger_proto_rawDescOnce sync.Once
	file_proto_logger_proto_rawDescData []byte
)

func file_proto_logger_proto_rawDescGZIP() []byte {
	file_proto_logger_proto_rawDescOnce.Do(func() {
		file_proto_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logger_proto_rawDesc), len(file_proto_logger_proto_rawDesc)))
	})
	return file_proto_logger_proto_rawDescData
}

var file_proto_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logger_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: logger.LogRequest
	(*LogResponse)(nil), // 1: logger.LogResponse
}
var file_proto_logger_proto_depIdxs = []int32{
	0, // 0: logger.LoggerService.SaveLog:input_type -> logger.LogRequest
	1, // 1: logger.LoggerService.SaveLog:output_type -> logger.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logger_proto_init() }
func file_proto_logger_proto_init() {
	if File_proto_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logger_proto_rawDesc), len(file_proto_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logger_proto_goTypes,
		DependencyIndexes: file_proto_logger_proto_depIdxs,
		MessageInfos:      file_proto_logger_proto_msgTypes,
	}.Build()
	File_proto_logger_proto = out.File
	file_proto_logger_proto_goTypes = nil
	file_proto_logger_proto_depIdxs = nil
}
