// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: EmailSender/proto/mail.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRequest) Reset() {
	*x = MailRequest{}
	mi := &file_EmailSender_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRequest) ProtoMessage() {}

func (x *MailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EmailSender_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRequest.ProtoReflect.Descriptor instead.
func (*MailRequest) Descriptor() ([]byte, []int) {
	return file_EmailSender_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailResponse) Reset() {
	*x = MailResponse{}
	mi := &file_EmailSender_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailResponse) ProtoMessage() {}

func (x *MailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EmailSender_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailResponse.ProtoReflect.Descriptor instead.
func (*MailResponse) Descriptor() ([]byte, []int) {
	return file_EmailSender_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_EmailSender_proto_mail_proto protoreflect.FileDescriptor

const file_EmailSender_proto_mail_proto_rawDesc = "" +
	"\n" +
	"\x1cEmailSender/proto/mail.proto\x12\x04mail\"K\n" +
	"\vMailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"B\n" +
	"\fMailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2=\n" +
	"\bSendMail\x121\n" +
	"\bSendMail\x12\x11.mail.MailRequest\x1a\x12.mail.MailResponseB\x12Z\x10./notificationpbb\x06proto3"

var (
	file_EmailSender_proto_mail_proto_rawDescOnce sync.Once
	file_EmailSender_proto_mail_proto_rawDescData []byte
)

func file_EmailSender_proto_mail_proto_rawDescGZIP() []byte {
	file_EmailSender_proto_mail_proto_rawDescOnce.Do(func() {
		file_EmailSender_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EmailSender_proto_mail_proto_rawDesc), len(file_EmailSender_proto_mail_proto_rawDesc)))
	})
	return file_EmailSender_proto_mail_proto_rawDescData
}

var file_EmailSender_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_EmailSender_proto_mail_proto_goTypes = []any{
	(*MailRequest)(nil),  // 0: mail.MailRequest
	(*MailResponse)(nil), // 1: mail.MailResponse
}
var file_EmailSender_proto_mail_proto_depIdxs = []int32{
	0, // 0: mail.SendMail.SendMail:input_type -> mail.MailRequest
	1, // 1: mail.SendMail.SendMail:output_type -> mail.MailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EmailSender_proto_mail_proto_init() }
func file_EmailSender_proto_mail_proto_init() {
	if File_EmailSender_proto_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EmailSender_proto_mail_proto_rawDesc), len(file_EmailSender_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EmailSender_proto_mail_proto_goTypes,
		DependencyIndexes: file_EmailSender_proto_mail_proto_depIdxs,
		MessageInfos:      file_EmailSender_proto_mail_proto_msgTypes,
	}.Build()
	File_EmailSender_proto_mail_proto = out.File
	file_EmailSender_proto_mail_proto_goTypes = nil
	file_EmailSender_proto_mail_proto_depIdxs = nil
}
